---
kind: Service
apiVersion: v1
metadata:
  name: fosspay
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:102409834926:certificate/391c5233-9d97-4013-9cc1-9bc85716053b
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  selector:
    app: fosspay
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fosspay
  namespace: sponsorship
  labels:
    app: fosspay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fosspay
  template:
    metadata:
      labels:
        app: fosspay
    spec:
      containers:
        - name: fosspay
          image: gcr.io/sponsorship-263515/sponsorship:29.12.19
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - name: config
              mountPath: "/etc/fosspay"
              readOnly: true

      volumes:
        - name: config
          secret:
            secretName: fosspay
