---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres11
  namespace: sponsorship
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Service
apiVersion: v1
metadata:
  name: postgres11
  namespace: sponsorship
spec:
  selector:
    app: postgres11
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres11
  namespace: sponsorship
spec:
  serviceName: postgres11
  replicas: 1
  selector:
    matchLabels:
      app: postgres11
  updateStrategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: postgres11
    spec:
      containers:
        - name: postgres
          image: postgres:11.4-alpine
          resources:
            requests:
              memory: "192Mi"
              cpu: 0.001
          args: ["postgres", "-c", "wal_level=logical"]
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              value: app_admin
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: postgres11
